[account]
orderId = ""
userId = ""
Cookie = ""
carshopCookie = ""
deviceToken = ""

[notice]
deliveryTimeLatest = "锁定订单后预计24-27周交付，预计还需6-9周"
carshopNotice = ""
remarks = "--来自Github Action"
errorTimes = 0
orderStatus = 2520
